// Upload a resume
// Fetch resumes by role
import { uploadData } from 'aws-amplify/storage';
// import { listResumes } from './graphql/queries'; // Generated by Amplify

export const uploadResume = async (file, role) => {
  try {
    const result = await Storage.put(`resumes/${file.name}`, file, {
      contentType: file.type,
    });
    //TODO: ... update DynamoDB with resume metadata
    console.log("result: ", result);
  } catch (error) {
    console.error('Error uploading file: ', error);
  }
};


// export const fetchResumesByRole = async (role) => {
//   try {
//     const resumeData = await graphql(
//       graphqlOperation(listResumes, { filter: { role: { eq: role } } })
//     );
//     return resumeData.data.listResumes.items;
//   } catch (error) {
//     console.error('Error fetching resumes: ', error);
//   }
// };